//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpamTools.lib.Data.EFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerTsask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchedulerTsask()
        {
            this.EmailList = new HashSet<EmailList>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailList> EmailList { get; set; }
        public virtual Server Server { get; set; }
        public virtual EmailSender EmailSender { get; set; }
    }
}
